evenement-parcours-integration:
  - nom: Point accueil
    description:
    type-declancheur: s
    valeur-declancheur: 0
    type: Parcours intégration
    cycle: false
    type-recurrence:
    valeur-recurrence:
    nb_jour_avant_rappel: 15
    destinataire-groupe:
      - rh
  - nom: Entretien etonnement
    description: Rh fait un mail à direction, manager proximité, commercial
    type-declancheur: m
    valeur-declancheur: 2
    type: Parcours intégration
    cycle: false
    type-recurrence:
    valeur-recurrence:
    nb_jour_avant_rappel: 15
    destinataire-groupe:
      - manager
      - commerce
  - nom: Point fin de période d'éssai
    description: Manager doit déterminer les objectifs en fonction du point de mission
    type-declancheur: m
    valeur-declancheur: 3
    type: Parcours intégration
    cycle: false
    type-recurrence:
    valeur-recurrence:
    nb_jour_avant_rappel: 15
    destinataire-groupe:
      - manager
  - nom: Visite médicale
    description: RH doit prévenir et convenir d'une date pour la visite médicale
    type-declancheur: m
    valeur-declancheur: 4
    type: Visite médicale
    cycle: true
    type-recurrence: a
    valeur-recurrence: 4
    nb_jour_avant_rappel: 30
    destinataire-groupe:
      - rh